package ar.wildstyle.valuegenerator;

/**
 * {@code ValueGenerator} is interface for classes which generate values of the given type.
 *
 * @author Adam Rosini
 */
public interface ValueGenerator<T> {

   /**
    * Generates and returns a value.
    */
   public abstract T generateValue();

   /**
    * Returns the type of values generated by this value generator.
    *
    * @post return != null
    */
   public abstract Class<T> getValueType();

   /**
    * Returns true if this value generator may generate a null value, false otherwise. If the default implementation for this method is not
    * applicable to this value generator's implementation, this method must be overridden.
    */
   default public boolean canGenerateNull() {
      try {
         final double nullChance = (double)this.getClass().getDeclaredField("nullChance").get(this);
         return nullChance > 0;
      }
      catch (final Exception e) {
         return false;
      }
   }

}
